"""added site model

Revision ID: 356ed64a7415
Revises: e6b7f9a07b22
Create Date: 2025-03-16 12:56:28.879246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356ed64a7415'
down_revision = 'e6b7f9a07b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_images_site_id", 'sites', ['site_id'], ['id'])
        batch_op.drop_column('site')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint("fk_images_site_id", type_='foreignkey')

    # ### end Alembic commands ###
