"""empty message

Revision ID: de219581479d
Revises: 
Create Date: 2025-03-13 13:40:44.636983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de219581479d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('eye_side', sa.Enum('LEFT', 'RIGHT', name='eyeside'), nullable=False),
    sa.Column('quality_score', sa.Enum('LOW', 'ACCEPTABLE', 'HIGH', name='imagequalityscore'), nullable=False),
    sa.Column('anatomy_score', sa.Enum('POOR', 'ACCEPTABLE', 'GOOD', name='anatomyscore'), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('over_illuminated', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('patients')
    # ### end Alembic commands ###
