"""Initial

Revision ID: e6b7f9a07b22
Revises: 
Create Date: 2025-03-15 16:22:10.204345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b7f9a07b22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('eye_side', sa.Enum('LEFT', 'RIGHT', name='eyeside'), nullable=False),
    sa.Column('quality_score', sa.Enum('LOW', 'ACCEPTABLE', 'HIGH', name='imagequalityscore'), nullable=True),
    sa.Column('anatomy_score', sa.Enum('POOR', 'ACCEPTABLE', 'GOOD', name='anatomyscore'), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('over_illuminated', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('patients')
    # ### end Alembic commands ###
